---
title: "HW4"
author: "Liam"
date: "2/5/2020"
output: html_document
---
## Question 1
```{r}
z <- 1.1^2.2^3.3
 print(z)
 z <- (1.1^2.2)^3.3
print(z)
z <- 3 * 1.1^3 + 2 * 1.1^2 + 1
print(z)
```
## Question 2
a
```{r}
?rep
rep(1:8)
c(rep(1:8),rep(7:1))
```
```{r}
?seq
c(seq(1:8),seq(7,1))
```
b
```{r}
?rep

```
```{r}
rep(1:5,c(1,2,3,4,5))
```

c
```{r}
rep(5:1,c(1,2,3,4,5))
```
### Question 3
```{r}
x <- runif(2)
```
```{r}
r <- sqrt(x[1]^2 + x[2]^2)
print(r)
```
```{r}
atan(x[2]/x[1])

```
#### Question 4
```{r}
queue <- c("sheep", "fox", "owl", "ant")
print(queue)
queue1 <- c(queue,"serpent")
print(queue1)
queue1[-1]
queue2 <- c(queue1[-1])
print(queue2)

queue3 <- c("donkey",queue2)
print(queue3)
queue3[-5]
queue4 <- c(queue3[-5])
print(queue4)
queue4[-3]
queue5 <- c(queue4[-3])
print(queue5)
append(queue5,"aphid",after=2)
queue6 <- c(append(queue5,"aphid",after=2))
print(queue6)
which(queue6 == "aphid")


```
##### Question 5
## Use R to create a vector of all of the integers from 1 to 100 that are not divisible by 2, 3, or 7.
```{r}
z <- seq(1:100)
z <- z[z %% 2!= 0 & z %% 3!= 0 & z %% 7!= 0]
print(z)


```









